apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-pod-8085-tcp-host
  labels:
    app: master-pod-8085-tcp-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-pod-8085-tcp-host

  template:
    metadata:
      labels:
        app: master-pod-8085-tcp-host
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: master
      hostNetwork: true
      tolerations:
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: master-pod-8085-tcp-host
          image: matmerr/toolbox:v6.1
          env:
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
          ports:
            - containerPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-pod-8085-tcp
  labels:
    app: master-pod-8085-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-pod-8085-tcp

  template:
    metadata:
      labels:
        app: master-pod-8085-tcp
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: master
      tolerations:
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: master-pod-8085-tcp
          image: matmerr/toolbox:v6.1
          env:
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
          ports:
            - containerPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-pod-8086-udp
  labels:
    app: master-pod-8086-udp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-pod-8086-udp
  template:
    metadata:
      labels:
        app: master-pod-8086-udp
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: master
      tolerations:
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: master-pod-udp
          image: matmerr/toolbox:v6.1
          env:
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
          ports:
            - containerPort: 8086
