---
apiVersion: v1
kind: Service
metadata:
  name: matmerr-http-v6
spec:
  ipFamily: IPv6
  type: LoadBalancer
  selector:
    app: matmerr-http-v6
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: matmerr-http-v4
spec:
  ipFamily: IPv4
  type: LoadBalancer
  selector:
    app: matmerr-http-v4
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matmerr-http-v6
  labels:
    app: matmerr-http-v6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matmerr-http-v6
  template:
    metadata:
      labels:
        app: matmerr-http-v6
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: agent
      containers:
        - name: matmerr-http-v6
          image: matmerr/toolbox:v6.2
          env:
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
            - name: HTTP_PORT
              value: "8081"
          ports:
            - containerPort: 8081
